name: Code quality check

on: [pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@1-add-cppcheck-args
      with:
        exclude_dir: lib
