name: Code quality check

on: [pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup env
      run: |
        sudo apt-get update

        sudo apt-get install -y xorg-dev
        sudo apt-get install -y libc++-9-dev
        echo "::set-env name=CXX::clang++-9"

        sudo apt-get install -y cppcheck
        sudo apt-get install -y clang-tidy

        cmake -E make_directory ${{runner.workspace}}/build

    - name: cppcheck
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
        cppcheck src --enable=all --project=compile_commands.json -i$GITHUB_WORKSPACE/lib
