name: Ubuntu

on: [pull_request]

env:
  BUILD_TYPE: Release
  CXX: clang++

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install dependencies
      run: |
        sudo apt-get update

        sudo apt-get install -y xorg-dev libc++-10-dev llvm-dev libubsan0 iwyu
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS_AS_ERRORS=ON\
          -DENABLE_INCLUDE_WHAT_YOU_USE=ON -DENABLE_SANITIZER_ADDRESS=ON -DENABLE_SANITIZER_UNDEFINED_BEHAVIOR=ON\
          -DENABLE_SANITIZER_LEAK=ON -DUNITY_BUILD=ON -DASSIMP_BUILD_TESTS=0

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE 2> >(tee "output.txt")

    - name: Post PR comment for warnings/errors
      if: ${{ always() }}
      uses: JacobDomagala/CompileResultAction@master
      with:
        comment_title: UBUNTU COMPILE RESULT
        compile_result_file: ${{runner.workspace}}/build/output.txt
